sudo: required
services:
- docker
env:
  - PATH=$PATH:${HOME}/google-cloud-sdk/bin
language: node_js
node_js:
- '5'
# cache:
#   directories:
#   - "$HOME/google-cloud-sdk/"
before_install:
- openssl aes-256-cbc -K $encrypted_61002d288013_key -iv $encrypted_61002d288013_iv
  -in client-secret.json.enc -out client-secret.json -d
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
    curl https://sdk.cloud.google.com | bash;
  fi
- gcloud version
- which gcloud
- ${HOME}/google-cloud-sdk/bin/gcloud version
- gcloud auth activate-service-account --key-file client-secret.json
- gcloud config set project ${PROJECT_ID}
install:
- gcloud -q components update kubectl
- gcloud container clusters get-credentials ${CLUSTER_ID} --zone ${ZONE_ID}
before_script:
- npm install -g webpack
script:
- npm run test
- npm run docker-builder
- npm run docker
after_success:
- gcloud docker push ${DOCKER_IMAGE}:${IMAGE_TAG:-latest}
- kubectl rolling-update deployment ${DEPLOYMENT_NAME} --image ${DOCKER_IMAGE}:${IMAGE_TAG:-latest}
