sudo: required
services:
  - docker
  - gcloud
language: node_js
node_js:
  - "5"
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
before_install:
  # install google cloud sdk if not there
  - if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash; fi
  - export PATH=${HOME}/google-cloud-sdk/bin:${PATH}
  - pip install PyOpenSSL
  # Start auth
  # GCLOUD_CLIENT_SECRET is a base64 encoded client-secret.json file from
  # Google Credentials Console
  - echo ${GCLOUD_CLIENT_SECRET} | base64 -d > client-secret.json
  - head -n 3 client-secret.json
  - gcloud auth activate-service-account ${GCLOUD_SERVICE_ACCOUNT} --key-file client-secret.json
  # End auth
  - gcloud config set project ${PROJECT_ID}
install:
  - gcloud -q components update kubectl
  - gcloud container clusters get-credentials ${CLUSTER_ID} --zone ${ZONE_ID}
before_script:
  - npm install -g webpack
script:
  - npm run test
  - npm run docker-builder
  - npm run docker
after_success:
  - gcloud docker push ${DOCKER_IMAGE}:${IMAGE_TAG:-latest}
  - kubectl rolling-update deployment ${DEPLOYMENT_NAME} --image ${DOCKER_IMAGE}:${IMAGE_TAG:-latest}
