apiVersion: v1
kind: Service
metadata:
  name: www-klumhru-com-public
spec:
  type: LoadBalancer
  selector:
    name: www-klumhru-com-deployment
    tier: frontend
  ports:
    - port: 80
      name: http
