apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: www-klumhru-com-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        name: www-klumhru-com-deployment
    spec:
      containers:
        - name: www-klumhru-com
          image: IMAGE_FULL
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
